### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by mcmingchang** [QiaoranC/tf_ResNeSt_RegNet_model#1]
tensorflow-gpu==2.1.0

  File "F:\tf_ResNeSt_RegNet_model-master\models\ResNest.py", line 87, in __call__
    filters = inputs.shape[self._channel_axis].value
AttributeError: 'int' object has no attribute 'value'

**Comment by mcmingchang** [comment]
I modified it to 'filters = inputs.shape[self._channel_axis]'

**Comment by QiaoranC** [comment]
Thanks, 
i test it under tensorflow-gpu==1.15, very similar to 2.X style.
I will upgrade to 2.1 and update the code.
