### ISSUE TITLE
How i feed imagenet data to resnetst

### ISSUE THREAD

**Issue by xiaokangyu** [QiaoranC/tf_ResNeSt_RegNet_model#12]
hi thank you for your code about resnetst.my issue is how  i feed imagenet data to resnetst.  thank you .Looking forward to your reply.

**Comment by QiaoranC** [comment]
I hardly use imagenet or other super large public dataset, i mostly use private dataset. 
But i think what you need is dataloader tutorial, which tensorflow have lots of them.
