### ISSUE TITLE
3D ResNest for Pytorch

### ISSUE THREAD

**Issue by CVAPPS24** [QiaoranC/tf_ResNeSt_RegNet_model#13]
Are there any guidelines to implement ResNest 3D for Pytorch?

Thanks.

**Comment by QiaoranC** [comment]
sorry for the long time reply, this reply may too late for you, just in case, there are plenty resource for pytorch, if i want change it to ResNest 3D, replace the conv2d to conv3d and do some change for the input shape. it should work. But i am worry the resource consumer would be too high.
