### ISSUE TITLE
网络部署没有问题，但不能训练（tensorflow-gpu-1.15.0）

### ISSUE THREAD

**Issue by wuguoqingfudan** [QiaoranC/tf_ResNeSt_RegNet_model#17]
UnknownError: 2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node conv2d/Conv2D}}]]
	 [[loss/mul/_2675]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node conv2d/Conv2D}}]]
0 successful operations.
0 derived errors ignored.

**Comment by QiaoranC** [comment]
sorry for the long time reply, you surely solved the problem , just in case, it seems the cudnn problem, if you want train it, you probably need GPU, or disable gpu. 
like `export CUDA_VISIBLE_DEVICES=-1` before `python train.py`
