### ISSUE TITLE
How to load the pretrained model? I have train a .h5 file in the VOC but I dont't know how to load it

### ISSUE THREAD

**Issue by ShihuaiXu** [QiaoranC/tf_ResNeSt_RegNet_model#18]
thank you in advance

**Comment by QiaoranC** [comment]
hi, it's a long time, and i guess you surely solve the problem. just in case, the official tensorflow has a details documentation code about how to train load model. very practical, the way i load is following. 
```
resnest50 = build_model(cfg)
checkpoint_rr = tf.train.Checkpoint(model=resnest50)
checkpoint_rr.restore(model_path)
```
