### ISSUE TITLE
Groups = 2

### ISSUE THREAD

**Issue by JeremyOng96** [QiaoranC/tf_ResNeSt_RegNet_model#20]
Hi,

From the code, when groups = 2, will the summation of radix be mixed up with other groups? For example, if there are 2 groups with 2 radices, each group must only sum up their respective radices i.e. group 1 sum radix 1 and radix 2 and group 2 sum radix 3 and radix 4. Is that the case with the code here? 

Thanks

**Comment by QiaoranC** [comment]
hi, sorry for the late reply, since its been a long time and resnest is quite complicated, i am not quite sure about this, if you are still interested, you may tried it with original authors.  Sorry again.
