### ISSUE TITLE
ValueError: Unrecognize model name resnest101

### ISSUE THREAD

**Issue by ptran1203** [QiaoranC/tf_ResNeSt_RegNet_model#21]
Hi, I'm trying to get ResNest model from models.model_factory but got the error

`ValueError: Unrecognize model name resnest101`

Possible the cause is [here](https://github.com/QiaoranC/tf_ResNeSt_RegNet_model/blob/master/models/model_factory.py#L97)  I think  it should  be  "elif"

I have created a [merge request](https://github.com/QiaoranC/tf_ResNeSt_RegNet_model/pull/22) for this issue, please help me to check it

Thank you!

**Comment by jasondolorso** [comment]
You're right on this one. The if statement resets on line 97, hence, will show an error if resnest or regnet is used.

**Comment by QiaoranC** [comment]
Thanks and sorry for the late reply, it is a mistake.
