### ISSUE TITLE
Accuracy for RegNet

### ISSUE THREAD

**Issue by AdityaKane2001** [QiaoranC/tf_ResNeSt_RegNet_model#26]
@QiaoranC  I'm trying to implement RegNetY on my own but I'm not able to achieve the accuracy mentioned in the paper. Did you face the same problem?

**Comment by innat** [comment]
@AdityaKane2001
It looks like he also faced such discrepancy, mentioned [in discussion section](https://github.com/QiaoranC/tf_ResNeSt_RegNet_model#discussion).
