### ISSUE TITLE
The ResNeSt 3D from tensorflow version  depends on your implement

### ISSUE THREAD

**Issue by ghost** [QiaoranC/tf_ResNeSt_RegNet_model#7]
I wrote a model of 3D Resnest references your code, and fixed few bugs come from the original copy, by the way. I will fork and update this if you interest in.

**Comment by QiaoranC** [comment]
@vitanuan Hi, i am interested in the bug fix, welcome to update it. I will check it. The 3D Resnest also sounds a good supplement.  
Cause i heard but never used 3D conv, I am wondering what kinds of task you are woking on? like medical image CT or video classification? Is 3D conv a main solution at moment? Cause i heard its cost is too high (from label annotation to model).
